<?php

namespace Proxies\__CG__\App\Mapper;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Confrontation extends \App\Mapper\Confrontation implements \Doctrine\ODM\MongoDB\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Mapper\\Confrontation' . "\0" . 'id', '' . "\0" . 'App\\Mapper\\Confrontation' . "\0" . 'player1', '' . "\0" . 'App\\Mapper\\Confrontation' . "\0" . 'player2', '' . "\0" . 'App\\Mapper\\Confrontation' . "\0" . 'winner', '' . "\0" . 'App\\Mapper\\Confrontation' . "\0" . 'stage', '' . "\0" . 'App\\Mapper\\Confrontation' . "\0" . 'order', '' . "\0" . 'App\\Mapper\\Confrontation' . "\0" . 'logJson'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Mapper\\Confrontation' . "\0" . 'id', '' . "\0" . 'App\\Mapper\\Confrontation' . "\0" . 'player1', '' . "\0" . 'App\\Mapper\\Confrontation' . "\0" . 'player2', '' . "\0" . 'App\\Mapper\\Confrontation' . "\0" . 'winner', '' . "\0" . 'App\\Mapper\\Confrontation' . "\0" . 'stage', '' . "\0" . 'App\\Mapper\\Confrontation' . "\0" . 'order', '' . "\0" . 'App\\Mapper\\Confrontation' . "\0" . 'logJson'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Confrontation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function start($gameClass)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'start', [$gameClass]);

        return parent::start($gameClass);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getPlayer1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlayer1', []);

        return parent::getPlayer1();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlayer1($player1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlayer1', [$player1]);

        return parent::setPlayer1($player1);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlayer2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlayer2', []);

        return parent::getPlayer2();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlayer2($player2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlayer2', [$player2]);

        return parent::setPlayer2($player2);
    }

    /**
     * {@inheritDoc}
     */
    public function getWinner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWinner', []);

        return parent::getWinner();
    }

    /**
     * {@inheritDoc}
     */
    public function getLogJson()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogJson', []);

        return parent::getLogJson();
    }

    /**
     * {@inheritDoc}
     */
    public function getStage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStage', []);

        return parent::getStage();
    }

    /**
     * {@inheritDoc}
     */
    public function setStage($key)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStage', [$key]);

        return parent::setStage($key);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrder', []);

        return parent::getOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrder($order)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrder', [$order]);

        return parent::setOrder($order);
    }

}
